export const CONSTANTS = {
  // Scheduler
  SCHEDULER_INTERVAL_MS: 60_000,
  AGENT_TIMEOUT_MS: 30_000,
  MAX_LOGS_IN_MEMORY: 50,
  HEALTH_CHECK_INTERVAL: 10,

  // Tatum
  TATUM_RATE_LIMIT_MS: 400,
  TATUM_RPC_TIMEOUT_MS: 10_000,
  TATUM_PRICE_TIMEOUT_MS: 5_000,

  // Walrus
  WALRUS_EPOCHS: 5,
  WALRUS_TIMEOUT_MS: 20_000,

  // Agent
  DEFAULT_DAILY_LIMIT: 10,
  MAX_INTENT_LENGTH: 500,
} as const;
